### ISSUE TITLE
build error(Subproject directory not found and Unity.wrap file not found)

### ISSUE THREAD

**Issue by shadowthreed** [brenns10/userspace_cooperative_multitasking#1]
Hello @brenns10 , I just cloned the project and ran `meson build`, then the ERROR is present as below:
> subprojects/sc-collections.git/meson.build:42:0: ERROR: Subproject directory not found and Unity.wrap file not found

Does it need to install `Unity.wrap` before building? If YES, how to? 
BTW, thanks for your high-quality blog.

**Comment by brenns10** [comment]
Hi @ShadowThree, thanks for reporting this. My sc-collections library, which is mostly just used for a convenient linked list implementation, added unit tests, and that Unity testing library is now pulled into the build for this repository. Which is wrong - tests should be enabled when developing the library, but not when using it.

That was wrong, so I fixed that. I'd recommend a `git pull`, then `git clean -ffdx` (assuming you don't have any local changes), then your `meson build` should work fine. Sorry for that snafu :)

Let me know if you still encounter issues! And if you enjoyed this post/example library, then you'd probably enjoy the more "production-ready" version I have [here](https://git.sr.ht/~brenns10/sc-lwt), which I've integrated into my [async signal bot](https://github.com/brenns10/cbot) to do lots of different I/O-bound tasks in one OS thread, but multiple userspace/green threads.
